'use strict';

const ALPHABET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
      CLASSNAME_LENGTH = 6,
      RANDOM_NUMBER_MAXIMUM = 1000000000;

module.exports = {
  ALPHABET,
  CLASSNAME_LENGTH,
  RANDOM_NUMBER_MAXIMUM
};
